# Development Environment Configuration
# Uses volumes to mount local code for hot-reloading.
services:
  db:
    image: pgvector/pgvector:pg17
    container_name: db_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432" # Expose PostgreSQL port for local debugging if needed
    env_file:
      - .env.dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend_dev
    build:
      context: ./backend
      target: dev # Use the 'dev' stage from the backend Dockerfile
    volumes:
      - ./backend:/backend # Mount local 'backend' folder into the container
      - /backend/.venv # Don't mount local .venv, use the one in the container
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_dev_data: